### ISSUE TITLE
ConnectWifi not connecting but opening Wifi dialog

### ISSUE THREAD

**Issue by sthewissen** [exendahal/maui_wifi_manager#28] opened 2024-12-10 14:20 UTC
I've been testing this library and noticed something I didn't quite expect. When calling `ConnectWifi` I would personally expect the device to connect to the Wi-Fi without my intervention as a user. However, what actually happens for me is that the Wi-Fi dialog from Android is popped up. I will have to then manually select my own Wi-Fi connection.

- Tested on an Android 13 and Android 14 device
- Permissions are all in place
- The Wi-Fi I want to connect to is valid and available (it's the second one in the list below)

![image](https://github.com/user-attachments/assets/feb96089-ad0c-4634-9288-5edc1c07e691)

**Comment by exendahal** [comment] 2024-12-10 16:02
Hello @sthewissen,
This is the expected behavior for this library.
Due to changes in the Android API starting from versions 10 and 11, we had to adopt different approaches for connecting to Wi-Fi networks. On Android 9 and lower, we can connect to Wi-Fi networks directly without requiring user prompts. On Android 10, we use the Wi-Fi Suggestion API to achieve this. For newer versions, we introduce a mechanism to add a Wi-Fi network and display a connection dialog, enabling users to connect seamlessly without manually adding the network.
We feel these approaches strike a good balance between usability and compatibility across the wide range of Android API levels.

**Comment by sthewissen** [comment] 2024-12-11 12:31
Ok, clear! The Android Wi-Fi story seems very messy, riddled with deprecation, and no clear-cut alternatives. Unfortunate, but I guess the days of just doing this kind of stuff without user intervention are over.

**Comment by exendahal** [comment] 2024-12-11 16:56
Agreed, it’s a tricky situation with all the deprecations and the need for user involvement.

**Comment by exendahal** [comment] 2024-12-13 15:54
I believe we have agreed that user involvement is necessary to connect to Wi-Fi. If there are no further issues, I will go ahead and close this issue.

**Closed** 2024-12-16 08:15 UTC
Labels: question
